### ISSUE TITLE
Checkouts redirect to 404

### ISSUE THREAD

**Issue by kobykotiv** [frontvibe/fluid#150]
In my production environment checkouts redirect to a 404.

https://kobykotiv.com

https://www.kobykotiv.com/cart/c/c1-e444c1371664a14823833f03bd632f3b?key=7cf9de8eba28d60bc8e8cfdbbe6e2122

![Screenshot_20240415_095807_Chrome](https://github.com/frontvibe/fluid/assets/23111682/36bd86f0-8fea-455d-82c2-9681c41a5d4f)

**Comment by kobykotiv** [comment]
OK. I did that and NOW the checkouts redirect to a myshopify checkout. the domain name is kobys-ai-apparel.myshopify.com and NOT my actual domain name. Is this a limitation of Hydrogen? How can I resolve this? I want my domain to be the one customers see. ?...?

**Comment by thomasKn** [comment]
Did you add a specific subdomain (like `checkout.kobykotiv.com`) to your Shopify store?

The checkout subdomain should be configured as the primary domain of your Online Store:

![image](https://github.com/frontvibe/fluid/assets/10447155/e88cce4e-1487-4bd6-9f0d-c908e2a49e10)

**Comment by kobykotiv** [comment]
I have my fluid fork deployed to vercel. It didn't work on shopify oxygen. 🤔

**Comment by thomasKn** [comment]
Checkout is managed by Shopify so checkout subdomain needs to be configured on Shopify side.
