### ISSUE TITLE
How to add Google Analytics?

### ISSUE THREAD

**Issue by kobykotiv** [frontvibe/fluid#153]
I'm trying to add Google Analytics [like this](https://community.shopify.com/c/technical-q-a/integrating-google-analytics-with-hydrogen-2-0/m-p/2170045). But i'm having issues. 
![image](https://github.com/frontvibe/fluid/assets/23111682/b0471209-95a3-46fd-8e7f-698b57b969fc)

When I inspect element I try to find the G-Tag object in the Network Tab like i'm supposed to. But it's not there.

**Comment by thomasKn** [comment]
Here is my recommendation:
1) Implement Google Tag Manager via the Hydrogen [Script component](https://shopify.dev/docs/api/hydrogen/2023-10/components/script)
2) Set up Google Analytics from your GTM container
3) Send events to GTM via the [CustomAnalytics component](https://github.com/frontvibe/fluid/blob/main/app/components/CustomAnalytics.tsx)
